language: python
sudo: false
python:
  - "2.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # setup modelrunner
  - conda create -n modelrunner python=2.7
  - conda install --yes -c https://conda.anaconda.org/sel -n modelrunner modelrunner
services:
  - redis-server
before_script:
  # setup primary, worker(s)
  - source activate modelrunner
  - ./scripts/start_primary.sh
  - ./scripts/start_worker.sh test
  - ./scripts/start_worker.sh test_2
script:
  - echo "in script"
  - sleep 1
  - for pid_file in *.pid; do p=`cat $pid_file`; echo "$pid_file $p"; done
  # test job runs to completion and then another is killed
  - ./testing/test_full.sh localhost:8080
   # test 2 jobs created, one is killed, other runs to completion 
  - ./testing/test_queueing.sh localhost:8080
  
notifications:
  irc: "irc.freenode.org#sel-columbia"
